version: 2

refrences:
  ignored-branches: &ignored-branches
     branches:
      ignore:
        - gh-pages

  cache-options: &cache-options
    key: package-cache-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - run:
          name: test-reporter-setup
          command: npm install jest-junit --no-save
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: linter
          command: ./node_modules/.bin/standard
      - run:
          name: test-reporter-setup
          command: mkdir -p ./reports/junit
      - run:
          name: test
          command: ./node_modules/.bin/jest tests --ci --testResultsProcessor="jest-junit" --runInBand
          environment:
            NODE_ENV: test
            JEST_JUNIT_OUTPUT: reports/junit/jest.xml
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "90:b9:1e:76:c6:56:b2:6d:66:1f:ec:28:34:99:5f:ae"
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: deploy-gh-pages
          command: ./bin/deploy


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            <<: *ignored-branches

      - test:
          filters:
            <<: *ignored-branches
          requires:
            - build

      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
